/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Communication.RPC.Thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ThriftResponse : TBase
  {
    private string _RequestAddress;
    private string _Data;
    private string _ErrMsg;
    private ResponseStatus _Status;

    public string RequestAddress
    {
      get
      {
        return _RequestAddress;
      }
      set
      {
        __isset.RequestAddress = true;
        this._RequestAddress = value;
      }
    }

    public string Data
    {
      get
      {
        return _Data;
      }
      set
      {
        __isset.Data = true;
        this._Data = value;
      }
    }

    public string ErrMsg
    {
      get
      {
        return _ErrMsg;
      }
      set
      {
        __isset.ErrMsg = true;
        this._ErrMsg = value;
      }
    }

    public ResponseStatus Status
    {
      get
      {
        return _Status;
      }
      set
      {
        __isset.Status = true;
        this._Status = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool RequestAddress;
      public bool Data;
      public bool ErrMsg;
      public bool Status;
    }

    public ThriftResponse() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                RequestAddress = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Data = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                ErrMsg = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.I32) {
                Status = (ResponseStatus)iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ThriftResponse");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (RequestAddress != null && __isset.RequestAddress) {
          field.Name = "RequestAddress";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(RequestAddress);
          oprot.WriteFieldEnd();
        }
        if (Data != null && __isset.Data) {
          field.Name = "Data";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Data);
          oprot.WriteFieldEnd();
        }
        if (ErrMsg != null && __isset.ErrMsg) {
          field.Name = "ErrMsg";
          field.Type = TType.String;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(ErrMsg);
          oprot.WriteFieldEnd();
        }
        if (__isset.Status) {
          field.Name = "Status";
          field.Type = TType.I32;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32((int)Status);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ThriftResponse(");
      bool __first = true;
      if (RequestAddress != null && __isset.RequestAddress) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RequestAddress: ");
        __sb.Append(RequestAddress);
      }
      if (Data != null && __isset.Data) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Data: ");
        __sb.Append(Data);
      }
      if (ErrMsg != null && __isset.ErrMsg) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ErrMsg: ");
        __sb.Append(ErrMsg);
      }
      if (__isset.Status) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Status: ");
        __sb.Append(Status);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
