/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Communication.RPC.Thrift
{
  public enum ResponseStatus
  {
    Default = 0,
    Success = 1,
    Failed = 2,
    APINotFound = 3,
    VersionNotCompatible = 4,
    APINotImplemented = 5,
  }
}
